FROM --platform=linux/amd64 ghcr.io/conblem/sniproxy/rust as builder

WORKDIR /app
COPY Cargo.toml Cargo.lock /app/
COPY .cargo/config.toml .cargo/config.toml

COPY fake.rs src/main.rs
RUN cargo build --release --target=aarch64-unknown-linux-musl

COPY src src
RUN touch src/main.rs
RUN cargo build --release --target=aarch64-unknown-linux-musl

FROM scratch
WORKDIR /app

COPY --from=builder /app/target/aarch64-unknown-linux-musl/release/sniproxy /app/arm64