version: "3.9"

volumes:
  grafana-agent:


services:
  sniproxy:
    image: ghcr.io/conblem/sniproxy:main
    restart: unless-stopped
    command:
      [
        "--console-listen",
        "0.0.0.0",
        "--otel-endpoint",
        "http://grafana-agent:4317",
        "--dns",
        # Here you can specify your dns server which you would otherwise use
        # in your wireguard config
        "10.128.0.1:53"
      ]
    network_mode: "service:wireguard"
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    restart: unless-stopped
    ports:
      - "100.78.78.114:443:443"
      - "100.78.78.114:80:80"
      - "100.78.78.114:6669:6669"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./wireguard/wg0.conf:/config/wg0.conf:ro
  blocky:
    image: spx01/blocky:v0.22
    restart: unless-stopped
    ports:
      - "100.78.78.114:53:53/tcp"
      - "100.78.78.114:53:53/udp"
    volumes:
      - ./blocky/config.yml:/app/config.yml:ro
  grafana-agent:
    image: grafana/agent:v0.36.2
    restart: unless-stopped
    command:
      [
        "-config.expand-env",
        "-config.file",
        "/app/config.yml"
      ]
    ports:
      - "100.78.78.114:4317:4317"
    volumes:
      - ./grafana-agent/config.yml:/app/config.yml:ro
      - grafana-agent:/etc/agent/data
    environment:
      - TEMPO_USERNAME=${TEMPO_USERNAME}
      - TEMPO_API_KEY=${TEMPO_API_KEY}
