[build]
rustflags = [
    "--cfg", "tokio_unstable",
]

[target.x86_64-unknown-linux-musl]
#linker = "gcc"
rustflags = [
    "--cfg", "tokio_unstable",
    #"-C", "link-arg=--ld-path=/usr/bin/mold",
#    "-C", "target-feature=+crt-static",
#    "-C", "link-arg=-lgcc"
]
