name: Rust
on:
  pull_request:
    branches:
      - "**"
jobs:
  arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.arm64
          push: false
          cache-from: type=registry,ref=ghcr.io/conblem/sniproxy/cache
          cache-to: type=registry,ref=ghcr.io/conblem/sniproxy/cache,mode=max
