name: PR
on:
  pull_request:
    branches:
      - "**"
jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          file: Dockerfile.${{ matrix.arch }}
          push: false
          cache-from: type=registry,ref=ghcr.io/conblem/sniproxy/cache
          cache-to: type=registry,ref=ghcr.io/conblem/sniproxy/cache,mode=max
