name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          tags: ghcr.io/conblem/sniproxy:main-${{ matrix.arch }}
          file: Dockerfile.${{ matrix.arch }}
          platforms: linux/${{ matrix.arch }}
          push: true
          cache-from: type=registry,ref=ghcr.io/conblem/sniproxy/cache-${{ matrix.arch }}
          cache-to: type=registry,ref=ghcr.io/conblem/sniproxy/cache-${{ matrix.arch}},mode=max
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: int128/docker-manifest-create-action@v1
        with:
          tags: ghcr.io/conblem/sniproxy:main
          suffixes: |
            -amd64
            -arm64
