name: Rust
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - "**"
jobs:
  arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-arm64-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-musl --release
      - uses: actions/upload-artifact@v3
        with:
          name: arm64
          path: target/aarch64-unknown-linux-musl/release/sniproxy
  amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-amd64-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-musl --release
      - uses: actions/upload-artifact@v3
        with:
          name: amd64
          path: target/x86_64-unknown-linux-musl/release/sniproxy
  docker:
    runs-on: ubuntu-latest
    needs: [arm64, amd64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: arm64
      - uses: actions/download-artifact@v3
        with:
          name: amd64
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: conblem/sniproxy:latest
          platforms: linux/amd64,linux/arm64
